// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositorio.Implements;

namespace Repositorio.Migrations
{
    [DbContext(typeof(BankContext))]
    partial class BankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaBancario.Model.Client", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cuentaid")
                        .HasColumnType("int");

                    b.Property<int?>("Personaid")
                        .HasColumnType("int");

                    b.Property<int>("cliente_id")
                        .HasColumnType("int");

                    b.Property<string>("contrasenia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("estado_cliente")
                        .HasColumnType("bit");

                    b.Property<string>("identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Cuentaid");

                    b.HasIndex("Personaid");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("SistemaBancario.Model.Cuenta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cliente_id")
                        .HasColumnType("int");

                    b.Property<bool>("estado_cuenta")
                        .HasColumnType("bit");

                    b.Property<string>("numero_cuenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("saldo_inicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tipo_cuenta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Cuenta");
                });

            modelBuilder.Entity("SistemaBancario.Model.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("SistemaBancario.Model.Client", b =>
                {
                    b.HasOne("SistemaBancario.Model.Cuenta", null)
                        .WithMany("Cliente")
                        .HasForeignKey("Cuentaid");

                    b.HasOne("SistemaBancario.Model.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("Personaid");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SistemaBancario.Model.Cuenta", b =>
                {
                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
